SB-24793 -  Adding cassandra write consistency level to the job.
project-sunbird/sunbird-analytics-core pull request #109
Opened 2021-09-01 15:46 UTC by manjudr

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-02 16:33 UTC, maheshkumargangula approved these changes

2021-09-07 04:29 UTC, anandp504 requested changes

2021-09-07 04:29 UTC, anandp504 commented on analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
> +                      sparkRedisPort: Option[AnyRef] = Option("6379"), writeConsistencyLevel: Option[String] = None): SparkSession = {
Please use a default consistency level in the function parameter.

2021-09-07 04:29 UTC, anandp504 commented on analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
>          conf.set("spark.cassandra.input.consistency.level", readConsistencyLevel.get)
Please use getOrElse on an Option

2021-09-07 04:29 UTC, anandp504 commented on analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
> +        conf.set("spark.cassandra.output.consistency.level", writeConsistencyLevel.get)
Please use getOrElse on an Option.

2021-09-08 04:57 UTC, anandp504 approved these changes
Approved

2021-09-08 05:38 UTC, merged